### ISSUE TITLE
New window opening

### ISSUE THREAD

**Issue by KuntenRTX** [jerryoldson/Youtube-Music-RPC#1]
when I use the mousewheel click or ctrl + click, a new window is open.

the expected behaviour would be that those kind of actions don't do anything.  😁

![Captura de pantalla 2024-05-30 024229](https://github.com/jerryoldson/Youtube-Music-RPC/assets/166264444/a60c10d8-7457-4457-80a9-6d1d1da10395)

**Comment by jerryoldson** [comment]
Thanks for your issue, this problem has been solved with v1.0.2
